### ISSUE TITLE
Please add documentation on what to expect as successful output

### ISSUE THREAD

**Issue by mig5** [jenkinsci-cert/SECURITY-218#4]
Can you confirm this is the expected output indicating a success after running the script via /script ?

Result: [hudson.model.ManageJenkinsAction@335d5786, com.cloudbees.plugins.credentials.SystemCredentialsProvider$UserFacingAction@351d38c2, hudson.model.EnvironmentContributor$EnvVarsHtml@117963cc, hudson.model.MyViewsProperty$GlobalAction@3886ef0a, hudson.plugins.git.GitStatus@22b79684, hudson.security.WhoAmI@42fac5ea, jenkins.model.RunIdMigrator$UnmigrationInstruction@5dd7a800, org.jenkinsci.plugins.scriptsecurity.scripts.ScriptApproval@7956c821]

One server I got this, not sure if it represents a failure:

Result: [hudson.model.ManageJenkinsAction@2e9b56ec, #<Jenkins::Model::UnprotectedRootActionProxy:0x36106d0d>, #<Jenkins::Model::UnprotectedRootActionProxy:0x700dd36f>, com.cloudbees.jenkins.GitHubWebHook@25fea043, com.cloudbees.plugins.credentials.SystemCredentialsProvider$UserFacingAction@6fcba231, hudson.model.EnvironmentContributor$EnvVarsHtml@2205784e, hudson.model.MyViewsProperty$GlobalAction@151d5a55, hudson.plugins.git.GitStatus@3a158d47, hudson.scm.SubversionStatus@5cee4e1b, hudson.security.WhoAmI@2149fe47, jenkins.model.RunIdMigrator$UnmigrationInstruction@d4f864, org.jenkinsci.plugins.scriptsecurity.scripts.ScriptApproval@1dff6da9]

**Comment by mig5** [comment]
Additionally, how do I know it has worked e.g should the X-Jenkins-CLI-Port / X-Jenkins-CLI2-Port headers no longer appear or be running on those ports? Mine still are..

**Comment by mig5** [comment]
Confirming for anyone else who wonders the same thing. Checking that /cli/ gives a 404 after running the script (instead of a helper page of CLI sub commands), seems to indicate it worked regardless of output like above.

**Comment by kohsuke** [comment]
I've updated README to reflect this. Thanks.

**Comment by mig5** [comment]
I get:

java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at hudson.cli.CLI.connectViaCliPort(CLI.java:210)
	at hudson.cli.CLI.<init>(CLI.java:128)
	at hudson.cli.CLIConnectionFactory.connect(CLIConnectionFactory.java:72)
	at hudson.cli.CLI._main(CLI.java:479)
	at hudson.cli.CLI.main(CLI.java:390)
	Suppressed: java.io.IOException: Server returned HTTP response code: 403 for URL: https:/example.com/cli
		at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1627)
		at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
		at hudson.cli.FullDuplexHttpStream.<init>(FullDuplexHttpStream.java:78)
		at hudson.cli.CLI.connectViaHttp(CLI.java:158)
		at hudson.cli.CLI.<init>(CLI.java:132)
		... 3 more


That's not the same EOF output as in your README. The 403, does it imply Jenkins instances that have security enabled (e.g require login to do anything) aren't vulnerable?

Thanks

**Comment by mig5** [comment]
I ran the cli.jar from a remote location. When I run the cli.jar locally to the Jenkins server I get the same EOFException as described in the README. Leaving this here in case anyone else like me is still confused. Thanks.

**Comment by daniel-beck** [comment]
@mig5 

> The 403, does it imply Jenkins instances that have security enabled (e.g require login to do anything) aren't vulnerable?

No. It's just that `/cli` is a special class of URL in Jenkins that is available without protection. However, when you remove it (which is what the mitigation script does), Jenkins will send a 403 while unauthenticated (or rather, when you don't have *Overall/Read*) because that's what it does for every URL (try e.g. `/foo` to see it's true). Only once you authenticate would you get a 404 indicating that there's nothing there.
